#!/system/bin/sh
set -e

SWAP_DEVICES="vnswap0"
SWAP_SIZE="262262784"

for SWAP_DEVICE in $SWAP_DEVICES; do
	if [[ -e "/sys/block/$SWAP_DEVICE/disksize" && -e "/dev/block/$SWAP_DEVICE" ]]; then
		echo "$SWAP_SIZE" > "/sys/block/$SWAP_DEVICE/disksize"
		mkswap "/dev/block/$SWAP_DEVICE"
		swapon "/dev/block/$SWAP_DEVICE"
	fi
done

exit 0
